export interface DiscoveryItem {
  id: string;
  name: string;
  location: string;
  category: "Park" | "Community Center" | "Pool" | "Landmark" | "Viewpoint";
  zipcode: string;
}

export const DISCOVERY_ITEMS: DiscoveryItem[] = [
  // --- PARKS (100+) ---
  { id: "p1", name: "Discovery Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p2", name: "Magnolia Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p3", name: "Volunteer Park", location: "Capitol Hill", category: "Park", zipcode: "98102" },
  { id: "p4", name: "Seward Park", location: "Rainier Valley", category: "Park", zipcode: "98118" },
  { id: "p5", name: "Alki Beach Park", location: "West Seattle", category: "Park", zipcode: "98116" },
  { id: "p6", name: "Green Lake Park", location: "Green Lake", category: "Park", zipcode: "98115" },
  { id: "p7", name: "Gas Works Park", location: "Wallingford", category: "Park", zipcode: "98103" },
  { id: "p8", name: "Golden Gardens Park", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p9", name: "Washington Park Arboretum", location: "Madison Park", category: "Park", zipcode: "98112" },
  { id: "p10", name: "Ravenna Park", location: "Ravenna", category: "Park", zipcode: "98105" },
  { id: "p11", name: "Carkeek Park", location: "Broadview", category: "Park", zipcode: "98177" },
  { id: "p12", name: "Lincoln Park", location: "West Seattle", category: "Park", zipcode: "98136" },
  { id: "p13", name: "Kubota Garden", location: "Rainier Beach", category: "Park", zipcode: "98178" },
  { id: "p14", name: "Cal Anderson Park", location: "Capitol Hill", category: "Park", zipcode: "98122" },
  { id: "p15", name: "Warren G. Magnuson Park", location: "Sand Point", category: "Park", zipcode: "98115" },
  { id: "p16", name: "Myrtle Edwards Park", location: "Downtown", category: "Park", zipcode: "98121" },
  { id: "p17", name: "Olympic Sculpture Park", location: "Downtown", category: "Park", zipcode: "98121" },
  { id: "p18", name: "Kinnear Park", location: "Queen Anne", category: "Park", zipcode: "98119" },
  { id: "p19", name: "Parsons Gardens", location: "Queen Anne", category: "Park", zipcode: "98119" },
  { id: "p20", name: "Kerry Park", location: "Queen Anne", category: "Park", zipcode: "98119" },
  { id: "p21", name: "Bhy Kracke Park", location: "Queen Anne", category: "Park", zipcode: "98109" },
  { id: "p22", name: "Denny Park", location: "South Lake Union", category: "Park", zipcode: "98109" },
  { id: "p23", name: "Cascade Playground", location: "South Lake Union", category: "Park", zipcode: "98109" },
  { id: "p24", name: "Lake Union Park", location: "South Lake Union", category: "Park", zipcode: "98109" },
  { id: "p25", name: "Victor Steinbrueck Park", location: "Downtown", category: "Park", zipcode: "98101" },
  { id: "p26", name: "Waterfront Park", location: "Downtown", category: "Park", zipcode: "98101" },
  { id: "p27", name: "Pioneer Square Park", location: "Pioneer Square", category: "Park", zipcode: "98104" },
  { id: "p28", name: "Occidental Square", location: "Pioneer Square", category: "Park", zipcode: "98104" },
  { id: "p29", name: "Hing Hay Park", location: "International District", category: "Park", zipcode: "98104" },
  { id: "p30", name: "Kobe Terrace Park", location: "International District", category: "Park", zipcode: "98104" },
  { id: "p31", name: "Yesler Terrace Park", location: "First Hill", category: "Park", zipcode: "98104" },
  { id: "p32", name: "Freeway Park", location: "Downtown", category: "Park", zipcode: "98101" },
  { id: "p33", name: "Plymouth Pillars Park", location: "First Hill", category: "Park", zipcode: "98122" },
  { id: "p34", name: "First Hill Park", location: "First Hill", category: "Park", zipcode: "98104" },
  { id: "p35", name: "Tashkent Park", location: "Capitol Hill", category: "Park", zipcode: "98102" },
  { id: "p36", name: "Seven Hills Park", location: "Capitol Hill", category: "Park", zipcode: "98122" },
  { id: "p37", name: "Miller Playfield", location: "Capitol Hill", category: "Park", zipcode: "98112" },
  { id: "p38", name: "Interlaken Park", location: "Capitol Hill", category: "Park", zipcode: "98112" },
  { id: "p39", name: "Louisa Boren Lookout", location: "Capitol Hill", category: "Park", zipcode: "98102" },
  { id: "p40", name: "Roanoke Park", location: "Capitol Hill", category: "Park", zipcode: "98102" },
  { id: "p41", name: "Montlake Playfield", location: "Montlake", category: "Park", zipcode: "98112" },
  { id: "p42", name: "Madison Park", location: "Madison Park", category: "Park", zipcode: "98112" },
  { id: "p43", name: "Madrona Park", location: "Madrona", category: "Park", zipcode: "98122" },
  { id: "p44", name: "Leschi Park", location: "Leschi", category: "Park", zipcode: "98122" },
  { id: "p45", name: "Frink Park", location: "Leschi", category: "Park", zipcode: "98144" },
  { id: "p46", name: "Colman Park", location: "Mount Baker", category: "Park", zipcode: "98144" },
  { id: "p47", name: "Mount Baker Park", location: "Mount Baker", category: "Park", zipcode: "98144" },
  { id: "p48", name: "Genesee Park", location: "Columbia City", category: "Park", zipcode: "98118" },
  { id: "p49", name: "Columbia Park", location: "Columbia City", category: "Park", zipcode: "98118" },
  { id: "p50", name: "Othello Park", location: "Othello", category: "Park", zipcode: "98118" },
  { id: "p51", name: "Pritchard Island Beach", location: "Rainier Beach", category: "Park", zipcode: "98118" },
  { id: "p52", name: "Beer Sheva Park", location: "Rainier Beach", category: "Park", zipcode: "98118" },
  { id: "p53", name: "Atlantic City Boat Ramp", location: "Rainier Beach", category: "Park", zipcode: "98118" },
  { id: "p54", name: "Lakeridge Park", location: "Rainier Beach", category: "Park", zipcode: "98178" },
  { id: "p55", name: "Skyway Park", location: "Skyway", category: "Park", zipcode: "98178" },
  { id: "p56", name: "Jefferson Park", location: "Beacon Hill", category: "Park", zipcode: "98108" },
  { id: "p57", name: "Daejeon Park", location: "Beacon Hill", category: "Park", zipcode: "98144" },
  { id: "p58", name: "Dr. Jose Rizal Park", location: "Beacon Hill", category: "Park", zipcode: "98144" },
  { id: "p59", name: "Lewis Park", location: "Beacon Hill", category: "Park", zipcode: "98144" },
  { id: "p60", name: "Sturgus Park", location: "Beacon Hill", category: "Park", zipcode: "98144" },
  { id: "p61", name: "Katie Black's Garden", location: "Beacon Hill", category: "Park", zipcode: "98144" },
  { id: "p62", name: "Van Asselt Playground", location: "Beacon Hill", category: "Park", zipcode: "98108" },
  { id: "p63", name: "Georgetown Playfield", location: "Georgetown", category: "Park", zipcode: "98108" },
  { id: "p64", name: "Oxbow Park", location: "Georgetown", category: "Park", zipcode: "98108" },
  { id: "p65", name: "Duwamish Waterway Park", location: "South Park", category: "Park", zipcode: "98108" },
  { id: "p66", name: "Cesar Chavez Park", location: "South Park", category: "Park", zipcode: "98108" },
  { id: "p67", name: "Marra-Desimone Park", location: "South Park", category: "Park", zipcode: "98108" },
  { id: "p68", name: "Westcrest Park", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p69", name: "Riverview Playfield", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p70", name: "High Highland Park", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p71", name: "Roxhill Park", location: "West Seattle", category: "Park", zipcode: "98126" },
  { id: "p72", name: "EC Hughes Playground", location: "West Seattle", category: "Park", zipcode: "98126" },
  { id: "p73", name: "Delridge Playfield", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p74", name: "Camp Long", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p75", name: "Dragonfly Pavilion", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p76", name: "Fairmount Park", location: "West Seattle", category: "Park", zipcode: "98136" },
  { id: "p77", name: "Lowman Beach Park", location: "West Seattle", category: "Park", zipcode: "98136" },
  { id: "p78", name: "Solstice Park", location: "West Seattle", category: "Park", zipcode: "98136" },
  { id: "p79", name: "Me-Kwa-Mooks Park", location: "West Seattle", category: "Park", zipcode: "98136" },
  { id: "p80", name: "Emma Schmitz Memorial Overlook", location: "West Seattle", category: "Park", zipcode: "98136" },
  { id: "p81", name: "Constellation Park", location: "West Seattle", category: "Park", zipcode: "98116" },
  { id: "p82", name: "Hamilton Viewpoint Park", location: "West Seattle", category: "Park", zipcode: "98116" },
  { id: "p83", name: "Don Armeni Boat Ramp", location: "West Seattle", category: "Park", zipcode: "98116" },
  { id: "p84", name: "Seacrest Park", location: "West Seattle", category: "Park", zipcode: "98116" },
  { id: "p85", name: "Jack Block Park", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p86", name: "Pigeon Point Park", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p87", name: "Puget Park", location: "West Seattle", category: "Park", zipcode: "98106" },
  { id: "p88", name: "Soundview Terrace", location: "Queen Anne", category: "Park", zipcode: "98119" },
  { id: "p89", name: "Marshall Park", location: "Queen Anne", category: "Park", zipcode: "98119" },
  { id: "p90", name: "Smith Cove Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p91", name: "Ella Bailey Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p92", name: "Ursula Judkins Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p93", name: "Kiwanis Memorial Preserve Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p94", name: "Bayview Playground", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p95", name: "Lawton Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p96", name: "Pleasant Valley Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p97", name: "Briarcliff Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p98", name: "Commodore Park", location: "Magnolia", category: "Park", zipcode: "98199" },
  { id: "p99", name: "Kirke Park", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p100", name: "Salmon Bay Park", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p101", name: "Ballard Commons Park", location: "Ballard", category: "Park", zipcode: "98107" },
  { id: "p102", name: "Marvin's Garden", location: "Ballard", category: "Park", zipcode: "98107" },
  { id: "p103", name: "Bergen Place", location: "Ballard", category: "Park", zipcode: "98107" },
  { id: "p104", name: "Webster Park", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p105", name: "Loyal Heights Playfield", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p106", name: "Sunset Park", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p107", name: "Shilshole Bay Marina", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p108", name: "Whittier Heights Pocket Park", location: "Ballard", category: "Park", zipcode: "98117" },
  { id: "p109", name: "Snoqualmie Park", location: "Ballard", category: "Park", zipcode: "98117" },

  // --- COMMUNITY CENTERS & POOLS (50+) ---
  { id: "cc1", name: "Ballard Community Center", location: "Ballard", category: "Community Center", zipcode: "98117" },
  { id: "cc2", name: "Bitter Lake Community Center", location: "Broadview", category: "Community Center", zipcode: "98133" },
  { id: "cc3", name: "Delridge Community Center", location: "West Seattle", category: "Community Center", zipcode: "98106" },
  { id: "cc4", name: "Garfield Community Center", location: "Central District", category: "Community Center", zipcode: "98122" },
  { id: "cc5", name: "Green Lake Community Center", location: "Green Lake", category: "Community Center", zipcode: "98115" },
  { id: "cc6", name: "High Point Community Center", location: "West Seattle", category: "Community Center", zipcode: "98126" },
  { id: "cc7", name: "Jefferson Community Center", location: "Beacon Hill", category: "Community Center", zipcode: "98108" },
  { id: "cc8", name: "Loyal Heights Community Center", location: "Ballard", category: "Community Center", zipcode: "98117" },
  { id: "cc9", name: "Magnolia Community Center", location: "Magnolia", category: "Community Center", zipcode: "98199" },
  { id: "cc10", name: "Meadowbrook Community Center", location: "Lake City", category: "Community Center", zipcode: "98125" },
  { id: "cc11", name: "Miller Community Center", location: "Capitol Hill", category: "Community Center", zipcode: "98112" },
  { id: "cc12", name: "Montlake Community Center", location: "Montlake", category: "Community Center", zipcode: "98112" },
  { id: "cc13", name: "Northgate Community Center", location: "Northgate", category: "Community Center", zipcode: "98125" },
  { id: "cc14", name: "Queen Anne Community Center", location: "Queen Anne", category: "Community Center", zipcode: "98119" },
  { id: "cc15", name: "Rainier Community Center", location: "Rainier Valley", category: "Community Center", zipcode: "98118" },
  { id: "cc16", name: "Rainier Beach Community Center", location: "Rainier Beach", category: "Community Center", zipcode: "98118" },
  { id: "cc17", name: "Ravenna-Eckstein Community Center", location: "Ravenna", category: "Community Center", zipcode: "98115" },
  { id: "cc18", name: "South Park Community Center", location: "South Park", category: "Community Center", zipcode: "98108" },
  { id: "cc19", name: "Southwest Community Center", location: "West Seattle", category: "Community Center", zipcode: "98126" },
  { id: "cc20", name: "Van Asselt Community Center", location: "Beacon Hill", category: "Community Center", zipcode: "98108" },
  { id: "cc21", name: "Yesler Community Center", location: "First Hill", category: "Community Center", zipcode: "98104" },
  { id: "cc22", name: "International District/Chinatown CC", location: "International District", category: "Community Center", zipcode: "98104" },
  { id: "cc23", name: "Discovery Park Environmental Learning Center", location: "Magnolia", category: "Community Center", zipcode: "98199" },
  { id: "cc24", name: "Carkeek Park Environmental Learning Center", location: "Broadview", category: "Community Center", zipcode: "98177" },
  { id: "cc25", name: "Camp Long Lodge", location: "West Seattle", category: "Community Center", zipcode: "98106" },
  { id: "pool1", name: "Ballard Pool", location: "Ballard", category: "Pool", zipcode: "98107" },
  { id: "pool2", name: "Evans Pool", location: "Green Lake", category: "Pool", zipcode: "98115" },
  { id: "pool3", name: "Helene Madison Pool", location: "Haller Lake", category: "Pool", zipcode: "98133" },
  { id: "pool4", name: "Medgar Evers Pool", location: "Central District", category: "Pool", zipcode: "98122" },
  { id: "pool5", name: "Queen Anne Pool", location: "Queen Anne", category: "Pool", zipcode: "98119" },
  { id: "pool6", name: "Rainier Beach Pool", location: "Rainier Beach", category: "Pool", zipcode: "98118" },
  { id: "pool7", name: "Southwest Pool", location: "West Seattle", category: "Pool", zipcode: "98126" },
  { id: "pool8", name: "Meadowbrook Pool", location: "Lake City", category: "Pool", zipcode: "98125" },
  { id: "pool9", name: "Mounger Pool", location: "Magnolia", category: "Pool", zipcode: "98199" },
  { id: "pool10", name: "Colman Pool", location: "West Seattle", category: "Pool", zipcode: "98136" },
  { id: "cc26", name: "Hiawatha Community Center", location: "West Seattle", category: "Community Center", zipcode: "98116" },
  { id: "cc27", name: "Alki Community Center", location: "West Seattle", category: "Community Center", zipcode: "98116" },
  { id: "cc28", name: "Belltown Community Center", location: "Belltown", category: "Community Center", zipcode: "98121" },
  { id: "cc29", name: "Laurelhurst Community Center", location: "Laurelhurst", category: "Community Center", zipcode: "98105" },
  { id: "cc30", name: "Sand Point Community Center", location: "Sand Point", category: "Community Center", zipcode: "98115" },
  { id: "cc31", name: "Lake City Community Center", location: "Lake City", category: "Community Center", zipcode: "98125" },
  { id: "cc32", name: "Nathan Hale Community Center", location: "Lake City", category: "Community Center", zipcode: "98125" },
  { id: "cc33", name: "Phinney Center", location: "Phinney Ridge", category: "Community Center", zipcode: "98103" },
  { id: "cc34", name: "University Heights Center", location: "U-District", category: "Community Center", zipcode: "98105" },
  { id: "cc35", name: "Langston Hughes Performing Arts Institute", location: "Central District", category: "Community Center", zipcode: "98122" },
  { id: "cc36", name: "Pratt Fine Arts Center", location: "Central District", category: "Community Center", zipcode: "98144" },
  { id: "cc37", name: "Seattle Center Armory", location: "Downtown", category: "Community Center", zipcode: "98109" },
  { id: "cc38", name: "El Centro de la Raza", location: "Beacon Hill", category: "Community Center", zipcode: "98144" },
  { id: "cc39", name: "Daybreak Star Cultural Center", location: "Magnolia", category: "Community Center", zipcode: "98199" },
  { id: "cc40", name: "Nordic Museum", location: "Ballard", category: "Community Center", zipcode: "98107" },

  // --- LANDMARKS & VIEWPOINTS (100+) ---
  { id: "lm1", name: "Space Needle", location: "Lower Queen Anne", category: "Landmark", zipcode: "98109" },
  { id: "lm2", name: "Smith Tower", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm3", name: "Columbia Center", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm4", name: "Pike Place Market", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm5", name: "Seattle Public Library", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm6", name: "Museum of Flight", location: "Tukwila", category: "Landmark", zipcode: "98108" },
  { id: "lm7", name: "Museum of Pop Culture (MoPOP)", location: "Lower Queen Anne", category: "Landmark", zipcode: "98109" },
  { id: "lm8", name: "Pacific Science Center", location: "Lower Queen Anne", category: "Landmark", zipcode: "98109" },
  { id: "lm9", name: "Seattle Art Museum", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm10", name: "Frye Art Museum", location: "First Hill", category: "Landmark", zipcode: "98104" },
  { id: "lm11", name: "Wing Luke Museum", location: "International District", category: "Landmark", zipcode: "98104" },
  { id: "lm12", name: "Burke Museum", location: "U-District", category: "Landmark", zipcode: "98105" },
  { id: "lm13", name: "Henry Art Gallery", location: "U-District", category: "Landmark", zipcode: "98105" },
  { id: "lm14", name: "Living Computers: Museum + Labs", location: "SoDo", category: "Landmark", zipcode: "98134" },
  { id: "lm15", name: "Klondike Gold Rush National Historical Park", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm16", name: "The Spheres", location: "Downtown", category: "Landmark", zipcode: "98121" },
  { id: "lm17", name: "Ballard Locks", location: "Ballard", category: "Landmark", zipcode: "98107" },
  { id: "lm18", name: "Fremont Troll", location: "Fremont", category: "Landmark", zipcode: "98103" },
  { id: "lm19", name: "Gum Wall", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm20", name: "Seattle Great Wheel", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "vp1", name: "Kerry Park", location: "Queen Anne", category: "Viewpoint", zipcode: "98119" },
  { id: "vp2", name: "Gas Works Park", location: "Wallingford", category: "Viewpoint", zipcode: "98103" },
  { id: "vp3", name: "Ella Bailey Park View", location: "Magnolia", category: "Viewpoint", zipcode: "98199" },
  { id: "vp4", name: "Hamilton Viewpoint", location: "West Seattle", category: "Viewpoint", zipcode: "98116" },
  { id: "vp5", name: "Ursula Judkins Park View", location: "Magnolia", category: "Viewpoint", zipcode: "98199" },
  { id: "vp6", name: "Dr. Jose Rizal Park View", location: "Beacon Hill", category: "Viewpoint", zipcode: "98144" },
  { id: "vp7", name: "Bhy Kracke Park View", location: "Queen Anne", category: "Viewpoint", zipcode: "98109" },
  { id: "vp8", name: "Louisa Boren Park View", location: "Capitol Hill", category: "Viewpoint", zipcode: "98102" },
  { id: "vp9", name: "Volunteer Park Water Tower", location: "Capitol Hill", category: "Viewpoint", zipcode: "98102" },
  { id: "vp10", name: "Smith Tower Observatory", location: "Pioneer Square", category: "Viewpoint", zipcode: "98104" },
  { id: "vp11", name: "Sky View Observatory", location: "Downtown", category: "Viewpoint", zipcode: "98104" },
  { id: "vp12", name: "Space Needle Observation Deck", location: "Lower Queen Anne", category: "Viewpoint", zipcode: "98109" },
  { id: "vp13", name: "Mount Baker Ridge Viewpoint", location: "Mount Baker", category: "Viewpoint", zipcode: "98144" },
  { id: "vp14", name: "Belvedere Park View", location: "West Seattle", category: "Viewpoint", zipcode: "98116" },
  { id: "vp15", name: "Jack Block Park View", location: "West Seattle", category: "Viewpoint", zipcode: "98106" },
  { id: "vp16", name: "Charles Richey Sr Viewpoint", location: "West Seattle", category: "Viewpoint", zipcode: "98116" },
  { id: "vp17", name: "Duwamish Head Viewpoint", location: "West Seattle", category: "Viewpoint", zipcode: "98116" },
  { id: "vp18", name: "Sunset Hill Park View", location: "Ballard", category: "Viewpoint", zipcode: "98117" },
  { id: "vp19", name: "Golden Gardens Viewpoint", location: "Ballard", category: "Viewpoint", zipcode: "98117" },
  { id: "vp20", name: "Carkeek Park Beach View", location: "Broadview", category: "Viewpoint", zipcode: "98177" },
  { id: "lm21", name: "Rainier Tower", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm22", name: "Seattle Asian Art Museum", location: "Capitol Hill", category: "Landmark", zipcode: "98112" },
  { id: "lm23", name: "Volunteer Park Conservatory", location: "Capitol Hill", category: "Landmark", zipcode: "98102" },
  { id: "lm24", name: "Japanese Garden", location: "Madison Park", category: "Landmark", zipcode: "98112" },
  { id: "lm25", name: "Graham Visitors Center", location: "Madison Park", category: "Landmark", zipcode: "98112" },
  { id: "lm26", name: "Fishermen's Terminal", location: "Magnolia", category: "Landmark", zipcode: "98119" },
  { id: "lm27", name: "Hiram M. Chittenden Locks", location: "Ballard", category: "Landmark", zipcode: "98107" },
  { id: "lm28", name: "Fremont Bridge", location: "Fremont", category: "Landmark", zipcode: "98103" },
  { id: "lm29", name: "George Washington Memorial Bridge", location: "Fremont", category: "Landmark", zipcode: "98103" },
  { id: "lm30", name: "Montlake Bridge", location: "Montlake", category: "Landmark", zipcode: "98112" },
  { id: "lm31", name: "Lacey V. Murrow Memorial Bridge", location: "Mount Baker", category: "Landmark", zipcode: "98144" },
  { id: "lm32", name: "Alki Point Lighthouse", location: "West Seattle", category: "Landmark", zipcode: "98116" },
  { id: "lm33", name: "West Point Lighthouse", location: "Magnolia", category: "Landmark", zipcode: "98199" },
  { id: "lm34", name: "Seattle Waterfront", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm35", name: "Olympic Sculpture Park", location: "Downtown", category: "Landmark", zipcode: "98121" },
  { id: "lm36", name: "Myrtle Edwards Park", location: "Downtown", category: "Landmark", zipcode: "98121" },
  { id: "lm37", name: "Lake Union Park", location: "South Lake Union", category: "Landmark", zipcode: "98109" },
  { id: "lm38", name: "Center for Wooden Boats", location: "South Lake Union", category: "Landmark", zipcode: "98109" },
  { id: "lm39", name: "Museum of History & Industry (MOHAI)", location: "South Lake Union", category: "Landmark", zipcode: "98109" },
  { id: "lm40", name: "Seattle Center", location: "Lower Queen Anne", category: "Landmark", zipcode: "98109" },
  { id: "lm41", name: "KeyArena / Climate Pledge Arena", location: "Lower Queen Anne", category: "Landmark", zipcode: "98109" },
  { id: "lm42", name: "Memorial Stadium", location: "Lower Queen Anne", category: "Landmark", zipcode: "98109" },
  { id: "lm43", name: "McCaw Hall", location: "Lower Queen Anne", category: "Landmark", zipcode: "98109" },
  { id: "lm44", name: "Paramount Theatre", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm45", name: "Moore Theatre", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm46", name: "5th Avenue Theatre", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm47", name: "Benaroya Hall", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm48", name: "Showbox", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm49", name: "The Crocodile", location: "Belltown", category: "Landmark", zipcode: "98121" },
  { id: "lm50", name: "Neumos", location: "Capitol Hill", category: "Landmark", zipcode: "98122" },
  { id: "lm51", name: "Tractor Tavern", location: "Ballard", category: "Landmark", zipcode: "98107" },
  { id: "lm52", name: "Central Saloon", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm53", name: "Union Station", location: "International District", category: "Landmark", zipcode: "98104" },
  { id: "lm54", name: "King Street Station", location: "International District", category: "Landmark", zipcode: "98104" },
  { id: "lm55", name: "Seattle Ferry Terminal", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm56", name: "Pier 66 / Bell Street Pier", location: "Downtown", category: "Landmark", zipcode: "98121" },
  { id: "lm57", name: "Pier 55 / 56", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm58", name: "Ye Olde Curiosity Shop", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm59", name: "Ivar's Acres of Clams", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm60", name: "Edgewater Hotel", location: "Downtown", category: "Landmark", zipcode: "98121" },
  { id: "lm61", name: "Rainier Club", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm62", name: "Arctic Club Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm63", name: "Dexter Horton Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm64", name: "Hoge Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm65", name: "Seattle Tower", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm66", name: "Cobb Building", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm67", name: "Metropolitan Tract", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm68", name: "Sorrento Hotel", location: "First Hill", category: "Landmark", zipcode: "98104" },
  { id: "lm69", name: "Stimson-Green Mansion", location: "First Hill", category: "Landmark", zipcode: "98104" },
  { id: "lm70", name: "Dearborn House", location: "First Hill", category: "Landmark", zipcode: "98104" },
  { id: "lm71", name: "Epiphany Episcopal Church", location: "Madrona", category: "Landmark", zipcode: "98122" },
  { id: "lm72", name: "St. James Cathedral", location: "First Hill", category: "Landmark", zipcode: "98104" },
  { id: "lm73", name: "Plymouth Congregational Church", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm74", name: "Gethsemane Lutheran Church", location: "Downtown", category: "Landmark", zipcode: "98121" },
  { id: "lm75", name: "Immanuel Lutheran Church", location: "South Lake Union", category: "Landmark", zipcode: "98109" },
  { id: "lm76", name: "University Presbyterian Church", location: "U-District", category: "Landmark", zipcode: "98105" },
  { id: "lm77", name: "Blessed Sacrament Church", location: "U-District", category: "Landmark", zipcode: "98105" },
  { id: "lm78", name: "Mount Zion Baptist Church", location: "Central District", category: "Landmark", zipcode: "98122" },
  { id: "lm79", name: "Langston Hughes Performing Arts Center", location: "Central District", category: "Landmark", zipcode: "98122" },
  { id: "lm80", name: "Washington Hall", location: "Central District", category: "Landmark", zipcode: "98122" },
  { id: "lm81", name: "Nippon Kan Theatre", location: "International District", category: "Landmark", zipcode: "98104" },
  { id: "lm82", name: "Cadillac Hotel", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm83", name: "Metropole Building", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm84", name: "Grand Central Building", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm85", name: "Interurban Building", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm86", name: "Maynard Building", location: "Pioneer Square", category: "Landmark", zipcode: "98104" },
  { id: "lm87", name: "Pacific Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm88", name: "Lyon Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm89", name: "Exchange Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm90", name: "Norton Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm91", name: "Henry M. Jackson Federal Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm92", name: "United States Courthouse", location: "Downtown", category: "Landmark", zipcode: "98101" },
  { id: "lm93", name: "Seattle City Hall", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm94", name: "King County Courthouse", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm95", name: "King County Administration Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm96", name: "Yesler Building", location: "Downtown", category: "Landmark", zipcode: "98104" },
  { id: "lm97", name: "Harborview Medical Center", location: "First Hill", category: "Landmark", zipcode: "98104" },
  { id: "lm98", name: "Swedish Medical Center", location: "First Hill", category: "Landmark", zipcode: "98104" },
  { id: "lm99", name: "Virginia Mason Medical Center", location: "First Hill", category: "Landmark", zipcode: "98101" },
  { id: "lm100", name: "Seattle Children's Hospital", location: "Laurelhurst", category: "Landmark", zipcode: "98105" },
];

export function getDiscoveryItemsByZipcode(zipcode: string): DiscoveryItem[] {
  return DISCOVERY_ITEMS.filter((item) => item.zipcode === zipcode);
}

export function getAllDiscoveryItems(): DiscoveryItem[] {
  return DISCOVERY_ITEMS;
}

export const NEIGHBORHOODS = [
  "Ballard",
  "Pike-Pine",
  "Capitol Hill",
  "Denny Triangle",
  "First Hill",
  "South Lake Union",
  "Belltown",
  "U-District",
];

export interface Trail {
  id: string;
  name: string;
  distance: string;
  elevationGain: string;
  difficulty: "Easy" | "Moderate" | "Hard" | "Extreme" | "Strenuous";
  location: string;
  region: "I-90" | "Hwy 2" | "Mountain Loop" | "Rainier" | "Olympics" | "Highway 2";
}

export const TRAILS: Trail[] = [
  // I-90 Corridor
  { id: "t1", name: "Rattlesnake Ledge", distance: "4.0mi", elevationGain: "1160ft", difficulty: "Moderate", location: "North Bend", region: "I-90" },
  { id: "t2", name: "Mount Si", distance: "8.0mi", elevationGain: "3150ft", difficulty: "Strenuous", location: "North Bend", region: "I-90" },
  { id: "t3", name: "Snow Lake", distance: "7.2mi", elevationGain: "1800ft", difficulty: "Moderate", location: "Snoqualmie Pass", region: "I-90" },
  { id: "t4", name: "Mailbox Peak", distance: "9.4mi", elevationGain: "4000ft", difficulty: "Strenuous", location: "North Bend", region: "I-90" },
  { id: "t5", name: "Franklin Falls", distance: "2.0mi", elevationGain: "400ft", difficulty: "Easy", location: "Snoqualmie Pass", region: "I-90" },
  { id: "t6", name: "Twin Falls", distance: "3.6mi", elevationGain: "500ft", difficulty: "Moderate", location: "North Bend", region: "I-90" },
  { id: "t7", name: "Little Si", distance: "3.7mi", elevationGain: "1300ft", difficulty: "Moderate", location: "North Bend", region: "I-90" },
  { id: "t8", name: "Poo Poo Point", distance: "7.2mi", elevationGain: "1858ft", difficulty: "Moderate", location: "Issaquah", region: "I-90" },
  { id: "t9", name: "Granite Mountain", distance: "8.6mi", elevationGain: "3800ft", difficulty: "Strenuous", location: "Snoqualmie Pass", region: "I-90" },
  { id: "t10", name: "Bandera Mountain", distance: "8.0mi", elevationGain: "3400ft", difficulty: "Strenuous", location: "North Bend", region: "I-90" },
  { id: "t11", name: "Mount Teneriffe", distance: "13.8mi", elevationGain: "3800ft", difficulty: "Strenuous", location: "North Bend", region: "I-90" },
  { id: "t12", name: "Mason Lake", distance: "6.5mi", elevationGain: "2420ft", difficulty: "Moderate", location: "North Bend", region: "I-90" },
  { id: "t13", name: "Annette Lake", distance: "7.5mi", elevationGain: "1400ft", difficulty: "Moderate", location: "Snoqualmie Pass", region: "I-90" },
  { id: "t14", name: "Denny Creek", distance: "6.0mi", elevationGain: "1345ft", difficulty: "Moderate", location: "Snoqualmie Pass", region: "I-90" },
  { id: "t15", name: "Mirror Lake", distance: "3.0mi", elevationGain: "700ft", difficulty: "Easy", location: "Snoqualmie Pass", region: "I-90" },

  // Highway 2
  { id: "t16", name: "Lake Serene", distance: "8.2mi", elevationGain: "2000ft", difficulty: "Strenuous", location: "Index", region: "Highway 2" },
  { id: "t17", name: "Wallace Falls", distance: "5.6mi", elevationGain: "1300ft", difficulty: "Moderate", location: "Gold Bar", region: "Highway 2" },
  { id: "t18", name: "Colchuck Lake", distance: "8.0mi", elevationGain: "2280ft", difficulty: "Strenuous", location: "Leavenworth", region: "Highway 2" },
  { id: "t19", name: "Skyline Lake", distance: "3.0mi", elevationGain: "1100ft", difficulty: "Moderate", location: "Stevens Pass", region: "Highway 2" },
  { id: "t20", name: "Heybrook Lookout", distance: "2.6mi", elevationGain: "850ft", difficulty: "Easy", location: "Index", region: "Highway 2" },
  { id: "t21", name: "Minotaur Lake", distance: "3.5mi", elevationGain: "1900ft", difficulty: "Strenuous", location: "Stevens Pass", region: "Highway 2" },
  { id: "t22", name: "Blanca Lake", distance: "7.5mi", elevationGain: "3300ft", difficulty: "Strenuous", location: "Index", region: "Highway 2" },
  { id: "t23", name: "Beckler Peak", distance: "7.6mi", elevationGain: "2240ft", difficulty: "Moderate", location: "Skykomish", region: "Highway 2" },
  { id: "t24", name: "Hidden Lake Lookout", distance: "8.0mi", elevationGain: "3300ft", difficulty: "Strenuous", location: "Marblemount", region: "Highway 2" },
  { id: "t25", name: "Iron Goat Trail", distance: "6.0mi", elevationGain: "700ft", difficulty: "Easy", location: "Stevens Pass", region: "Highway 2" },
  { id: "t26", name: "Surprise Lake", distance: "8.0mi", elevationGain: "2300ft", difficulty: "Moderate", location: "Stevens Pass", region: "Highway 2" },
  { id: "t27", name: "Eightmile Lake", distance: "6.6mi", elevationGain: "1300ft", difficulty: "Moderate", location: "Leavenworth", region: "Highway 2" },
  { id: "t28", name: "Icicle Ridge", distance: "4.0mi", elevationGain: "1800ft", difficulty: "Moderate", location: "Leavenworth", region: "Highway 2" },
  { id: "t29", name: "Valhalla Mountain", distance: "7.0mi", elevationGain: "1500ft", difficulty: "Moderate", location: "Stevens Pass", region: "Highway 2" },
  { id: "t30", name: "Lichen Lake", distance: "8.0mi", elevationGain: "2000ft", difficulty: "Moderate", location: "Stevens Pass", region: "Highway 2" },

  // Mountain Loop
  { id: "t31", name: "Lake 22", distance: "5.4mi", elevationGain: "1350ft", difficulty: "Moderate", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t32", name: "Mount Pilchuck", distance: "5.4mi", elevationGain: "2300ft", difficulty: "Strenuous", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t33", name: "Heather Lake", distance: "4.6mi", elevationGain: "1034ft", difficulty: "Moderate", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t34", name: "Big Four Ice Caves", distance: "2.2mi", elevationGain: "220ft", difficulty: "Easy", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t35", name: "Gothic Basin", distance: "9.2mi", elevationGain: "2840ft", difficulty: "Strenuous", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t36", name: "Mount Dickerman", distance: "8.2mi", elevationGain: "3900ft", difficulty: "Strenuous", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t37", name: "Perry Creek", distance: "10.5mi", elevationGain: "3400ft", difficulty: "Strenuous", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t38", name: "Old Sauk River", distance: "6.0mi", elevationGain: "150ft", difficulty: "Easy", location: "Darrington", region: "Mountain Loop" },
  { id: "t39", name: "Lime Kiln Trail", distance: "7.0mi", elevationGain: "625ft", difficulty: "Easy", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t40", name: "Goat Lake", distance: "10.4mi", elevationGain: "1400ft", difficulty: "Moderate", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t41", name: "Lake Kelcema", distance: "1.0mi", elevationGain: "100ft", difficulty: "Easy", location: "Granite Falls", region: "Mountain Loop" },
  { id: "t42", name: "Sloan Peak", distance: "12.0mi", elevationGain: "5200ft", difficulty: "Extreme", location: "Darrington", region: "Mountain Loop" },
  { id: "t43", name: "Bedal Peak", distance: "5.0mi", elevationGain: "2900ft", difficulty: "Strenuous", location: "Darrington", region: "Mountain Loop" },
  { id: "t44", name: "White Chuck Bench", distance: "13.0mi", elevationGain: "1000ft", difficulty: "Moderate", location: "Darrington", region: "Mountain Loop" },
  { id: "t45", name: "North Fork Sauk River", distance: "17.0mi", elevationGain: "3000ft", difficulty: "Strenuous", location: "Darrington", region: "Mountain Loop" },

  // Rainier
  { id: "t46", name: "Skyline Trail", distance: "5.5mi", elevationGain: "1450ft", difficulty: "Strenuous", location: "Paradise", region: "Rainier" },
  { id: "t47", name: "Mount Fremont Lookout", distance: "5.6mi", elevationGain: "1200ft", difficulty: "Moderate", location: "Sunrise", region: "Rainier" },
  { id: "t48", name: "Tolmie Peak Lookout", distance: "7.5mi", elevationGain: "1540ft", difficulty: "Moderate", location: "Mowich Lake", region: "Rainier" },
  { id: "t49", name: "Naches Peak Loop", distance: "3.4mi", elevationGain: "600ft", difficulty: "Easy", location: "Chinook Pass", region: "Rainier" },
  { id: "t50", name: "Burroughs Mountain", distance: "9.0mi", elevationGain: "2500ft", difficulty: "Strenuous", location: "Sunrise", region: "Rainier" },
  { id: "t51", name: "Spray Park", distance: "8.0mi", elevationGain: "1700ft", difficulty: "Moderate", location: "Mowich Lake", region: "Rainier" },
  { id: "t52", name: "Comet Falls", distance: "3.8mi", elevationGain: "1250ft", difficulty: "Moderate", location: "Longmire", region: "Rainier" },
  { id: "t53", name: "Silver Falls", distance: "3.0mi", elevationGain: "300ft", difficulty: "Easy", location: "Ohanapecosh", region: "Rainier" },
  { id: "t54", name: "Grove of the Patriarchs", distance: "1.5mi", elevationGain: "50ft", difficulty: "Easy", location: "Ohanapecosh", region: "Rainier" },
  { id: "t55", name: "Summerland", distance: "8.4mi", elevationGain: "2100ft", difficulty: "Moderate", location: "Sunrise", region: "Rainier" },
  { id: "t56", name: "Dege Peak", distance: "4.2mi", elevationGain: "600ft", difficulty: "Easy", location: "Sunrise", region: "Rainier" },
  { id: "t57", name: "Glacier Basin", distance: "6.5mi", elevationGain: "1600ft", difficulty: "Moderate", location: "Sunrise", region: "Rainier" },
  { id: "t58", name: "Van Trump Park", distance: "6.0mi", elevationGain: "2150ft", difficulty: "Strenuous", location: "Longmire", region: "Rainier" },
  { id: "t59", name: "Pinnacle Peak", distance: "2.5mi", elevationGain: "1050ft", difficulty: "Moderate", location: "Paradise", region: "Rainier" },
  { id: "t60", name: "Camp Muir", distance: "9.0mi", elevationGain: "4600ft", difficulty: "Strenuous", location: "Paradise", region: "Rainier" },

  // Olympics
  { id: "t61", name: "Mount Storm King", distance: "4.0mi", elevationGain: "2065ft", difficulty: "Strenuous", location: "Lake Crescent", region: "Olympics" },
  { id: "t62", name: "Hurricane Hill", distance: "3.2mi", elevationGain: "700ft", difficulty: "Easy", location: "Hurricane Ridge", region: "Olympics" },
  { id: "t63", name: "Hall of Mosses", distance: "0.8mi", elevationGain: "100ft", difficulty: "Easy", location: "Hoh Rainforest", region: "Olympics" },
  { id: "t64", name: "Rialto Beach", distance: "4.0mi", elevationGain: "0ft", difficulty: "Easy", location: "Mora", region: "Olympics" },
  { id: "t65", name: "Sol Duc Falls", distance: "1.6mi", elevationGain: "200ft", difficulty: "Easy", location: "Sol Duc", region: "Olympics" },
  { id: "t66", name: "Marymere Falls", distance: "1.8mi", elevationGain: "500ft", difficulty: "Easy", location: "Lake Crescent", region: "Olympics" },
  { id: "t67", name: "Second Beach", distance: "4.0mi", elevationGain: "200ft", difficulty: "Easy", location: "La Push", region: "Olympics" },
  { id: "t68", name: "Ruby Beach", distance: "1.0mi", elevationGain: "50ft", difficulty: "Easy", location: "Kalaloch", region: "Olympics" },
  { id: "t69", name: "Klahhane Ridge", distance: "5.0mi", elevationGain: "1700ft", difficulty: "Moderate", location: "Hurricane Ridge", region: "Olympics" },
  { id: "t70", name: "Royal Basin", distance: "14.0mi", elevationGain: "3400ft", difficulty: "Strenuous", location: "Quilcene", region: "Olympics" },
  { id: "t71", name: "Marmot Pass", distance: "10.6mi", elevationGain: "3480ft", difficulty: "Strenuous", location: "Quilcene", region: "Olympics" },
  { id: "t72", name: "Mount Ellinor", distance: "6.2mi", elevationGain: "3300ft", difficulty: "Strenuous", location: "Hoodsport", region: "Olympics" },
  { id: "t73", name: "Lena Lake", distance: "6.4mi", elevationGain: "1300ft", difficulty: "Moderate", location: "Hoodsport", region: "Olympics" },
  { id: "t74", name: "Flapjack Lakes", distance: "15.4mi", elevationGain: "3050ft", difficulty: "Strenuous", location: "Hoodsport", region: "Olympics" },
  { id: "t75", name: "Enchanted Valley", distance: "26.0mi", elevationGain: "1700ft", difficulty: "Strenuous", location: "Quinault", region: "Olympics" },
];
